# Generated by Django 2.2.4 on 2020-03-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('primaryEmail', models.CharField(max_length=128)),
                ('secondaryEmail', models.CharField(max_length=128)),
            ],
        ),
    ]
