# Generated by Django 3.0.4 on 2020-03-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200322_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboardElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=300)),
                ('width', models.SmallIntegerField(default=350)),
                ('height', models.SmallIntegerField(default=350)),
            ],
        ),
    ]
