# Generated by Django 3.0.4 on 2020-03-23 13:08

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200322_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Blog', max_length=32)),
                ('info_banner', models.CharField(max_length=32)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
    ]
