# Generated by Django 3.0.4 on 2020-03-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='info_banner',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
