# Generated by Django 3.0.4 on 2020-03-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200323_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='primaryEmail',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='info_banner',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
