# Generated by Django 3.0.4 on 2020-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200328_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='landing_page_text',
            field=models.TextField(null=True),
        ),
    ]
